security:
    providers:
        our_db_provider:
            id: App\Security\UserProvider

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        App\Entity\Security\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login
                provider: our_db_provider
                use_referer: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration, roles: ROLE_ACMARCHE_ADMIN }
