vich_uploader:
    db_driver: orm

    mappings:
        acmarche_commerce_image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /data/commerces
            upload_destination: "%kernel.root_dir%/../public/data/commerces"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        acmarche_lunch_produit_image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /data/produits
            upload_destination: "%kernel.root_dir%/../public/data/produits"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        acmarche_lunch_categorie_image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /data/categories
            upload_destination: "%kernel.root_dir%/../public/data/categories"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
