<?php

namespace App\Repository\Quantite;

use Doctrine\ORM\EntityRepository;

/**
 * QuantiteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class QuantiteRepository extends EntityRepository
{
}
