<?php

namespace App\Repository\Livraison;

use App\Entity\Livraison\LieuLivraison;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * LieuxLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuxLivraisonRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, LieuLivraison::class);
    }

    /**
     * Pour remplir select du form
     * @return array
     */
    public function getForSearch()
    {
        $qb = $this->createQueryBuilder('lieux_livraison');

        $qb->orderBy('lieux_livraison.nom');
        $query = $qb->getQuery();

        $results = $query->getResult();
        $lieux = array();

        foreach ($results as $lieu) {
            $lieux[$lieu->getNom()] = $lieu->getId();
        }

        return $lieux;
    }
}
