<?php

namespace App\Repository\Categorie;

use App\Entity\Categorie\Categorie;
use App\Entity\Commerce\Commerce;
use App\Entity\Security\User;
use App\Entity\InterfaceDef\CategoryInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Categorie::class);
    }

    public function search($args)
    {
        $qb = $this->createQueryBuilder('categorie');
        $qb->leftJoin('categorie.produits', 'produits', 'WITH');
        $qb->addSelect('produits');

        $motclef = isset($args['motclef']) ? $args['motclef'] : null;
        $commerce = isset($args['commerce']) ? $args['commerce'] : null;

        if ($motclef) {
            $qb->andWhere('categorie.nom LIKE :clef')
                ->setParameter('clef', '%'.$motclef.'%');
        }

        $qb->addOrderBy('categorie.nom');

        return $qb->getQuery()->getResult();
    }

    public function getRoots()
    {
        $qb = $this->createQueryBuilder('categorie');

        $qb->andWhere('categorie.parent IS NULL');

        $qb->addOrderBy('categorie.nom');

        return $qb->getQuery()->getResult();
    }

    public function getEnfants(CategoryInterface $category)
    {
        $qb = $this->createQueryBuilder('categorie');

        $qb->andWhere('categorie.parent = :categorie')
            ->setParameter('categorie', $category);

        $qb->addOrderBy('categorie.nom');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @return Categorie[]
     */
    public function getOwnedByUser(User $user)
    {
        $em = $this->getEntityManager();
        $commerces = $em->getRepository(Commerce::class)->getCommercesOwnedByUser(
            $user
        );

        if (!$commerces) {
            return [];
        }

        return $this->search(['commerce' => $commerces]);
    }

}
