<?php

namespace App\Repository\Produit;

use App\Entity\Produit\ProduitImage;
use App\Entity\InterfaceDef\ProduitInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * ProduitImageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProduitImageRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProduitImage::class);
    }

    public function getImages(ProduitInterface $produit) {
        return $this->findBy(['produit'=>$produit],['position'=>'ASC']);
    }

}
