<?php

namespace App\Repository\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitDimensionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProduitDimensionRepository extends EntityRepository
{
}
