<?php

namespace App\Repository\Commande;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeProduitAttributRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommandeProduitAttributRepository extends EntityRepository
{
}
