<?php

namespace App\Repository\Commande;

/**
 * CommandeProduitSupplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProduitSupplementRepository extends \Doctrine\ORM\EntityRepository
{
}
